### PR TITLE
Changed container macro to is_container

### PR DESCRIPTION
**Pull request by xaocon**
The name change should make it easier to find and read.

falco-CLA-1.0-signed-off-by: Evan Pitstick <nerdx00@gmail.com>

### CODE REVIEW

**Comment by xaocon** [comment]
Not sure why it says it's missing the sign-off. It's there.

**Comment by xaocon** [comment]
I should have rebased instead of merging but everything seems to be passing now. I've got the sign-off in there so my guess is that the checker is looking for sysdig sign-off instead of falco like in it's details.

**Comment by mstemm** [comment]
Thanks--I want to figure out how widespread the use of the container macro is in user rules files, as this change would break those files, before merging. I'll try to check our sysdig secure customers first.

**Comment by mstemm** [comment]
It looks like the macro `container` is already pretty widely used in custom/user rules files, so changing the name of the macro from `container` to `is_container` would break those  user rules files. I guess you could *also* add an is_container macro that just pointed to macro, but that seems a bit redundant.

What do you think?

**Comment by mstemm** [comment]
We'll go ahead and close this PR for now. Feel free to make other changes if you'd like, though.

**Pull request closed without merging**
