### PR TITLE
Add fail2ban-server as spawn shell trusted binary

### PR DESCRIPTION
**Pull request by jcoetzee**
fail2ban spawns a shell to adjust iptables in order to ban/unban IP addresses.

### CODE REVIEW

**Comment by mstemm** [comment]
Looks great, thanks for the rule update.

**Comment by mstemm** [comment]
Oops, I forgot to ask for a contributor license agreement for the change. Could you re-submit this PR and in the commit that makes the change add the necessary signatures? We have instructions for doing that here: https://github.com/draios/falco#what-do-i-need-to-do-in-order-to-contribute-code.

Let me know if you have any questions.

**Comment by jcoetzee** [comment]
Think you'll have to revert the PR for be to resubmit it?

**Comment by mstemm** [comment]
Yes, I already reverted it.

**Pull request merged**
