### PR TITLE
Add base64 encoding and snap length support

### PR DESCRIPTION
**Pull request by zt2**
sysdig-CLA-1.0-signed-off-by: Yue Feng <ztz5651483@gmail.com>
falco-CLA-1.0-signed-off-by: Yue Feng <ztz5651483@gmail.com>

### CODE REVIEW

**Comment by zt2** [comment]
Have a look plz...
@mstemm

**Comment by mstemm** [comment]
The changes look good, and thanks for the contribution! I wanted to double check on the use case, though. Normally, most/all of the events that have an %evt.buffer that would be a candidate for display as base64 are also events that falco ignores. So I guess you have your own rules where you do use those events, and then also run falco with the `-A` flag?

**Comment by zt2** [comment]
> The changes look good, and thanks for the contribution! I wanted to double check on the use case, though. Normally, most/all of the events that have an %evt.buffer that would be a candidate for display as base64 are also events that falco ignores. So I guess you have your own rules where you do use those events, and then also run falco with the `-A` flag?

Yes, I use falco with `-A` and some custom rules to capture special system events. I'd like to use falco instead sysdig that's because rules in falco can be managed easily.  But some nice features in sysdig are missed in falco, like `%evt.buffer` (it can not display non ascii characters) and `snaplen` (can not custom `%evt.buffer` length).

There are other users has the same feature request please see https://github.com/draios/falco/issues/363

**Comment by mstemm** [comment]
Ok, I just wanted to make sure you knew about the required configuration. Merging, and thanks again!

**Pull request merged**
